In [2]:
import numpy as np

def stHOSVD_3d(A, r1, r2, r3):
# Construct Tucker decomposition of 3D tensor via stHOSVD with ranks [r1, r2, r3]
    N1,N2,N3 = A.shape
    A1=A.reshape(N1, N2 * N3)
    U, s, V = np.linalg.svd(A1, full_matrices=False)
    V1 = U[:,:r1]
    V1 = V1.T
    A1 = np.diag(s[:r1]) @ V[:r1,:] # r1 x N2*N3
    A1 = A1.reshape(r1, N2, N3)
    A1 = A1.transpose([0,2,1])
    A1 = A1.reshape(r1 * N3, N2) # r1 ∗ N3 x N2
    U, s, V = np.linalg.svd(A1, full_matrices=False)
    V2= V[:r2,:] # r2xN2
    U2 = U[:,:r2] @ np.diag(s[:r2]) # r1∗N3 x r2
    U2 = U2.reshape(r1, N3, r2) # r1 x N3 x r2
    U2 = U2.transpose([0,2,1]) # r1 x r2 x N3
    U2 = U2.reshape(r1 * r2, N3) # r1∗r2 x N3
    U, s, V = np.linalg.svd(U2, full_matrices=False)
    V3 = V[:r3,:] # U3(r3,j)
    G = U[:,:r3] @ np.diag(s[:r3])# r1 ∗ r2 x r3
    G = G.reshape(r1, r2, r3) # main core
    return G, V1, V2, V3

In [ ]:
def myMatrixIndexSumFunc(i,j,k):
    return i+j+k+3

N1 = N2 = N3 = 64
matr = np.fromfunction(myMatrixIndexSumFunc, [N1,N2,N3])

test = stHOSVD_3d(matr, 2 , 2)

In [12]:
a = np.ones((2,2,4))
b = np.ones((2,2,4))
print(a - b)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
